# Generated by Django 2.0.6 on 2018-07-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180702_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
