# Generated by Django 2.0.2 on 2018-03-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_player_signup_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplycode',
            name='value',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
