# Generated by Django 2.0.2 on 2018-03-19 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_supplycode_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_name',
            new_name='name',
        ),
    ]
