# Generated by Django 2.0.2 on 2018-03-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_game_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuplocation',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
