# Generated by Django 2.0.7 on 2018-07-09 02:26

import app.models.modifier
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180708_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modifier_type', enumfields.fields.EnumField(enum=app.models.modifier.ModifierType, max_length=1)),
                ('modifier_amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Faction')),
            ],
        ),
        migrations.AddField(
            model_name='supplycode',
            name='modifier',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='modifier',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Faction'),
        ),
    ]
