# Generated by Django 2.0.2 on 2018-03-20 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_signuplocation_is_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signuplocation',
            name='is_enabled',
        ),
    ]
