# Generated by Django 2.0.2 on 2018-03-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_signuplocation_is_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='in_oz_pool',
            field=models.BooleanField(default=False),
        ),
    ]
