# Generated by Django 2.0.7 on 2018-07-11 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20180711_0644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='modifier',
            new_name='point_modifier',
        ),
    ]
