# Generated by Django 2.0.8 on 2018-10-04 19:34

from django.db import migrations, models
import django.db.models.deletion


def add_game_to_signup_locations(apps, schema_editor):
    Game = apps.get_model('app', 'Game')
    SignupLocation = apps.get_model('app', 'SignupLocation')
    for sl in SignupLocation.objects.filter(game='908d7ce7-b9b6-4c09-babb-386c3cb13bbd'):
        game = Game.objects.first()
        sl.game = game
        sl.save()


def remove_game_from_signup_locations(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20180711_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuplocation',
            name='game',
            field=models.ForeignKey(default='908d7ce7-b9b6-4c09-babb-386c3cb13bbd', on_delete=django.db.models.deletion.PROTECT, to='app.Game'),
            preserve_default=False
        ),
        migrations.RunPython(
            code=add_game_to_signup_locations,
            reverse_code=remove_game_from_signup_locations,
        ),
    ]
