# Generated by Django 2.1 on 2018-10-27 22:34

from django.db import migrations, models


def remove_view_plugin_permissions(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    permissions = Permission.objects.filter(codename__startswith='view')
    permissions.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_add_game_to_signup_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementpage',
            name='viewable_by',
            field=models.CharField(choices=[('A', 'All'), ('H', 'Humans'), ('Z', 'Zombies')], max_length=1),
        ),
        migrations.AlterField(
            model_name='missionpage',
            name='viewable_by',
            field=models.CharField(choices=[('A', 'All'), ('H', 'Humans'), ('Z', 'Zombies')], max_length=1),
        ),
        migrations.RunPython(
            code=remove_view_plugin_permissions,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
