# Generated by Django 2.0.5 on 2018-05-20 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_player_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signuplocation',
            old_name='location',
            new_name='name',
        ),
    ]
