# Generated by Django 2.1.2 on 2018-10-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20181029_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signuplocation',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
