# Generated by Django 2.2.8 on 2019-12-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20191215_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='include_summary',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='is_oz',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
