# Generated by Django 2.2.8 on 2019-12-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20191215_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuplocation',
            name='fri_hours',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='signuplocation',
            name='mon_hours',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='signuplocation',
            name='thurs_hours',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='signuplocation',
            name='tues_hours',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='signuplocation',
            name='wed_hours',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
