# Generated by Django 2.2.8 on 2019-12-22 22:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20191219_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='legacy_points',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Legacy points'),
        ),
    ]
