# Generated by Django 2.2.8 on 2019-12-23 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_legacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legacy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_legacy', to=settings.AUTH_USER_MODEL),
        ),
    ]
