# Generated by Django 2.2.8 on 2019-12-29 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20191223_0723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legacy',
            old_name='cost',
            new_name='value',
        ),
    ]
