# Generated by Django 2.2.8 on 2019-12-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_moderator_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_score_public',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
