# Generated by Django 2.2.8 on 2019-12-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_player_is_score_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='is_score_public',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
