# Generated by Django 2.2.8 on 2019-12-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20191230_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='is_score_public',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
