# Generated by Django 3.1.1 on 2020-09-01 19:57

import app.models.email
import app.models.tag
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20191230_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='type',
            field=enumfields.fields.EnumField(default='S', enum=app.models.tag.TagType, max_length=1),
        ),
        migrations.AlterField(
            model_name='moderator',
            name='score',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name="Moderator 'score'. Can include letters. For fun."),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_score_public',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('data', models.CharField(max_length=32768)),
                ('group', enumfields.fields.EnumField(enum=app.models.email.RecipientGroup, max_length=1)),
                ('player_made', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.game')),
            ],
        ),
    ]
